In [2]:
import numpy as np

In [3]:
#delete
arr = np.array([4,6,7,34])
arr2= np.delete(arr, 1)
print(arr2)
print(type(arr))
print(len(arr))
print(arr.shape)

[ 4  7 34]
<class 'numpy.ndarray'>
4
(4,)


In [4]:
arr3=np.append(arr, [50,23,454])

In [5]:
#sorting

sorted_arr = np.sort(arr3)
print(sorted_arr)
print(sorted_arr[::-1])

[  4   6   7  23  34  50 454]
[454  50  34  23   7   6   4]


In [6]:
import numpy as np

lis = np.array([2,3,45,3])
print(lis+1)

[ 3  4 46  4]


In [7]:
class Polynomial:
    def __init__(self, num):
        self.num = num

    def __call__(self, x_arr):
        return x_arr

    def call(self, x_arr):
        return "count"


p = Polynomial(5)
print(p.call([56,5,6,7]))

count


In [8]:
import numpy as np

arr1 = np.array([2,34,45])
arr2 = 0

for i in range(4):
    arr2+=2*arr1
print(arr2)

[ 16 272 360]


In [9]:
#Write your code here

#using Polynomial Class and get_poly() method

#Part 1

class Polynomial:
    def __init__(self, coeff):
        self.coeff = coeff
        self.degree = len(coeff)-1

    def __call__(self, x_arr):
        p_x_arr= 0
        for i in range(self.degree+1):
            p_x_arr+=(self.coeff[i]*x_arr**i)
        
        return p_x_arr

   
#part 2

def get_poly(data_x,data_y):
    node1 = len(data_x)
    x_matrix = np.zeros((node1,node1))

    for i in range(node1):
        for j in range(node1):
            x_matrix[i,j] = data_x[i]**j
    
    xmat_inv = np.linalg.pinv(x_matrix)
    coeff = np.dot(xmat_inv, data_y)
    eq = Polynomial(coeff)
    return eq


#driver code

data_x = np.array([-0.5, 0, 0.5])
data_y = np.array([1.87, 2.20, 2.44])
poly = get_poly(data_x, data_y)
x_arr = np.array([6])
solution = poly(x_arr)
print("The value is",solution[0])
    

        


The value is -0.860000000000019


In [16]:
class Lagrange_Polynomial:
    def __init__(self, data_x, data_y):
        self.datax= data_x
        self.datay= data_y
        self.degree = len(data_x)-1


    def l(self, k, x):

        l_x = 1.0
        for i in range(self.degree+1):
            if i != k:
                self.x_i = self.datax[i]
                self.x_k = self.datax[k]
                l_x*=(x-self.x_i)/(self.x_k-self.x_i)

        return l_x
    

    def __call__(self, x_arr):

        p_x_arr = np.zeros(len(x_arr))
        for i,j in enumerate(x_arr):
            for k in range(self.degree+1):
                p_x_arr[i]+=self.datay[k]*self.l(k,j)

        return p_x_arr


# Driver Code

data_x = np.array([2, 4, 6])
data_y = np.array([8,16,24])
p = Lagrange_Polynomial(data_x,data_y)
x_arr = np.array([-1.5])
p_x = p(x_arr)
print(f"The value is {p_x[0]} by using Lagrange Interpolation")
f_x = 4*x_arr[0]
error = abs(f_x - p_x[0])
print("The actual interpolation error is",error)



[-6.]
The value is -6.0 by using Lagrange Interpolation
The actual interpolation error is 0.0
