In [1]:
import numpy as np

In [12]:
def create_fence(X, padding):
    x_row, x_col = X.shape
    fencedArr = np.zeros((x_row+(2*padding), x_col+(2*padding)), dtype = int)
    fr, fc = fencedArr.shape
    for i in range(fr):
        for j in range(fc):
            if (0<= i <= padding-1 or 2*padding+x_row<=i<fr-1):
                fencedArr[i][j] = 8
            else:
                if padding<=j<=fc-padding:
                    fencedArr[i][j] = X[i-padding-1][j-padding-1]
                else:
                    fencedArr[i][j] = 8
    return fencedArr



In [11]:
padding = 1
X = np.array([[2,3,4], [3,4,6], [2,1,4]])
print(create_fence(X, padding))

[[8 8 8 8 8]
 [8 4 2 1 4]
 [8 4 2 3 4]
 [8 6 3 4 6]
 [8 8 8 8 8]]


In [9]:
padding = 2
X = np.array([[2,3,4], [3,4,6], [2,1,4]])
print(create_fence(X, padding))

[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 4 2 1 4 8]
 [8 8 4 2 3 4 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]
